#!/usr/bin/env bash
set -euo pipefail

# Basic smoke tests + trigger supplier rate limiting.

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
demo_root="$(cd "$script_dir/.." && pwd)"
repo_root="$(cd "$demo_root/../.." && pwd)"
config_path="$demo_root/demo-config.json"

log_step() { echo; echo "[STEP] $*"; }
log_ok() { echo "[OK] $*"; }
log_info() { echo "[INFO] $*"; }
log_err() { echo "[ERROR] $*" >&2; }

die() { log_err "$*"; exit 1; }

maybe_start_azure_load_test_homepage_traffic() {
  # Optional: start 5 minutes of homepage traffic using Azure Load Testing (hosted JMeter).
  #
  # To enable, set:
  #   AZ_LOAD_TEST_RESOURCE   = Load Testing resource name or ARM ID
  # Optional:
  #   AZ_LOAD_TEST_RG         = resource group containing the Load Testing resource (defaults to Grocery RG)
  #   AZ_LOAD_TEST_ID         = test id to create/reuse (default: grocery-web-homepage-traffic)
  #   AZ_LOAD_TEST_USERS      = virtual users (default: 20)
  #   AZ_LOAD_TEST_RAMP_TIME  = ramp-up time in seconds (default: 20)
  #   AZ_LOAD_TEST_DURATION_SECONDS = test duration in seconds (default: 300)
  #
  # The test uses: loadtests/jmeter/groceryweb-homepage-random-traffic.jmx
  # and sets JMeter properties via --env (baseUrl, homePath).

  local load_test_resource="${AZ_LOAD_TEST_RESOURCE:-}"

  # Best-effort auto-discovery: if the caller didn't provide a resource name/id,
  # and there is exactly one Load Testing resource in the Grocery demo resource group, use it.
  if [[ -z "$load_test_resource" ]]; then
    if az load -h >/dev/null 2>&1; then
      local discovered
      discovered="$(az load list -g "$rg_name" --query "[].name" -o tsv 2>/dev/null || true)"
      if [[ -n "$discovered" ]]; then
        local count
        count="$(wc -l <<<"$discovered" | tr -d ' ')"
        if [[ "$count" == "1" ]]; then
          load_test_resource="$discovered"
          log_info "Auto-discovered Azure Load Testing resource in $rg_name: $load_test_resource"
        else
          log_info "Multiple Azure Load Testing resources found in $rg_name; set AZ_LOAD_TEST_RESOURCE to select one."
          return 0
        fi
      else
        log_info "Azure Load Testing not configured (AZ_LOAD_TEST_RESOURCE not set, and none discovered in $rg_name); skipping hosted JMeter homepage traffic."
        return 0
      fi
    else
      log_info "Azure Load Testing not configured (AZ_LOAD_TEST_RESOURCE not set); skipping hosted JMeter homepage traffic."
      return 0
    fi
  fi

  command -v az >/dev/null 2>&1 || die "Azure CLI (az) not found"

  local load_test_rg="${AZ_LOAD_TEST_RG:-$rg_name}"
  local test_id="${AZ_LOAD_TEST_ID:-grocery-web-homepage-traffic}"
  local users="${AZ_LOAD_TEST_USERS:-20}"
  local ramp_time="${AZ_LOAD_TEST_RAMP_TIME:-20}"
  local duration_seconds="${AZ_LOAD_TEST_DURATION_SECONDS:-300}"
  local run_id="grocery-web-traffic-$(date -u +%Y%m%d%H%M%S)"
  local jmx_path="$repo_root/loadtests/jmeter/groceryweb-homepage-random-traffic.jmx"

  [[ -f "$jmx_path" ]] || die "Missing JMeter test plan: $jmx_path"

  log_step "Azure Load Testing: start 5m random homepage traffic (hosted JMeter)"

  # Ensure the load extension is present.
  if ! az load -h >/dev/null 2>&1; then
    die "Azure CLI 'load' extension is not available. Install it with: az extension add --name load"
  fi

  # Create the test once (idempotent) if it doesn't exist.
  if ! az load test show -g "$load_test_rg" -n "$load_test_resource" -t "$test_id" >/dev/null 2>&1; then
    log_info "Creating Azure Load Testing test: $test_id"
    az load test create \
      --resource-group "$load_test_rg" \
      --load-test-resource "$load_test_resource" \
      --test-id "$test_id" \
      --test-type JMX \
      --test-plan "$jmx_path" \
      --display-name "Grocery Web - Homepage Random Traffic (5m)" \
      --description "Generated by Grocery demo trigger script; hits homepage with random think time for ~5 minutes." \
      --engine-instances 1 \
      --env baseUrl="$web_url" homePath="/" users="$users" rampTime="$ramp_time" durationSeconds="$duration_seconds" \
      >/dev/null
    log_ok "Created test $test_id"
  else
    log_info "Reusing existing Azure Load Testing test: $test_id"
  fi

  # Start a run (non-blocking; the run lasts ~5 minutes per the JMX scheduler).
  az load test-run create \
    --resource-group "$load_test_rg" \
    --load-test-resource "$load_test_resource" \
    --test-id "$test_id" \
    --test-run-id "$run_id" \
    --display-name "Grocery web traffic $(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    --env baseUrl="$web_url" homePath="/" users="$users" rampTime="$ramp_time" durationSeconds="$duration_seconds" \
    --no-wait \
    >/dev/null

  log_ok "Started Azure Load Testing run: $run_id (duration ~${duration_seconds}s)"
  log_info "Tip: check status with: az load test-run show -g \"$load_test_rg\" -n \"$load_test_resource\" -t \"$test_id\" -r \"$run_id\" -o table"
  log_info "Traffic settings: users=$users rampTime=$ramp_time durationSeconds=$duration_seconds"
}

command -v curl >/dev/null 2>&1 || die "curl not found"
command -v python3 >/dev/null 2>&1 || die "python3 not found (used for JSON parsing)"
command -v az >/dev/null 2>&1 || die "Azure CLI (az) not found"

[[ -f "$config_path" ]] || die "Missing $config_path. Run scripts/01-setup-demo.sh first."

api_url="$(python3 -c "import json; print(json.load(open('$config_path'))['ApiUrl'].rstrip('/'))")"
web_url="$(python3 -c "import json; print(json.load(open('$config_path'))['WebUrl'].rstrip('/'))")"
subscription_id="$(python3 -c "import json; print(json.load(open('$config_path'))['SubscriptionId'])")"
rg_name="$(python3 -c "import json; print(json.load(open('$config_path'))['ResourceGroupName'])")"
api_app_name="$(python3 -c "import json; print(json.load(open('$config_path'))['ApiContainerAppName'])")"

[[ -n "$api_url" ]] || die "ApiUrl missing in demo-config.json"
[[ -n "$web_url" ]] || die "WebUrl missing in demo-config.json"

log_step "Smoke: health endpoints"
curl -fsS "$api_url/health" >/dev/null && log_ok "API /health OK"
curl -fsS "$web_url/health" >/dev/null && log_ok "Web /health OK"

log_step "Smoke: list products"
curl -fsS "$api_url/api/products" >/dev/null && log_ok "API /api/products OK"

log_step "Prep: pin API to 1 replica (demo reliability)"
az account show >/dev/null 2>&1 || die "Azure CLI not logged in. Run: az login"
az account set --subscription "$subscription_id" >/dev/null

# Optional: start 5 minutes of random homepage traffic (Azure Load Testing / JMeter)
maybe_start_azure_load_test_homepage_traffic

az containerapp update -g "$rg_name" -n "$api_app_name" --min-replicas 1 --max-replicas 1 >/dev/null
log_ok "Pinned $api_app_name scale to 1 replica"

log_step "Trigger: hit inventory endpoint to induce 429s"
set +e
failures=0
for i in {1..60}; do
  code="$(curl -sS -o /dev/null -w "%{http_code}" "$api_url/api/products/PROD001/inventory")"
  if [[ "$code" == "503" ]]; then
    log_ok "Got 503 (supplier rate limit simulated) on attempt $i"
    failures=$((failures+1))
  fi
done
set -e

log_info "Observed 503 count: $failures"
log_ok "Done"
